all:
  hosts:
    osiris:
      # RPi 3 B+
      ansible_host: 192.168.1.101
    solaria:
      # RPi 3 B+
      ansible_host: 192.168.1.102

    galactica:
      # TrueNAS Custom
      # Intel Celeron G4900
      ansible_host: 192.168.1.121
    pacifica:
      # ASRock DeskMini 310
      # Intel Core i3-8100
      ansible_host: 192.168.1.122
    valkyrie:
      # Intel NUC D54250WYK
      # Intel Core i5-4250U
      ansible_host: 192.168.1.123
    archeron:
      # Acer Aspire A114
      # Intel Pentium Silver N5000
      ansible_host: 192.168.1.124

    pegasus:
      # HP EliteDesk 800 G1 DM
      # Intel Core i5-4590T
      ansible_host: 192.168.1.131
    ixion:
      # Dell Optiplex 7040M
      # Intel Core i7-6700T
      ansible_host: 192.168.1.132
    atlantia:
      # Lenovo Thinkcentre M700 Tiny
      # Intel Core i5-6400T
      ansible_host: 192.168.1.133
    rycon:
      # AMD Custom
      # AMD Ryzen 5 1600
      ansible_host: 192.168.1.134

    raptor:
      # RPi 4 2GB (plain debian 12 https://raspi.debian.net/)
      ansible_host: 192.168.1.141
      ansible_python_interpreter: /usr/bin/python3
      ansible_user: root
    viper:
      # RPi 4 2GB (plain debian 12 https://raspi.debian.net/)
      ansible_host: 192.168.1.142
      ansible_python_interpreter: /usr/bin/python3
      ansible_user: root
    blackbird:
      # RPi 4 2GB (plain debian 12 https://raspi.debian.net/)
      ansible_host: 192.168.1.143
      ansible_python_interpreter: /usr/bin/python3
      ansible_user: root

  children:
    rpi:
      children:
        blocky:
        storage:
    blocky:
      hosts:
        osiris:
        solaria:
    storage:
      hosts:
        raptor:
        viper:
        blackbird:
    debian:
      children:
        k8s_control_plane:
    ubuntu:
      children:
        blocky:
        k8s_workers:
    longhorn:
      hosts:
        pacifica:
        valkyrie:
        pegasus:
        ixion:
        atlantia:
        rycon:
    k8s_control_plane:
      hosts:
        pacifica:
        archeron:
        valkyrie:
    k8s_workers:
      hosts:
        pegasus:
        ixion:
        atlantia:
        rycon:
    k8s_cluster:
      children:
        k8s_control_plane:
        k8s_workers:
