all:
  hosts:
    osiris:
      # RPi 3 B+
      ansible_host: 192.168.1.101
      ansible_user: root
    solaria:
      # RPi 3 B+
      ansible_host: 192.168.1.102
      ansible_user: root

    galactica:
      # TrueNAS Custom
      # Intel Celeron G4900
      ansible_host: 192.168.1.121

    pacifica:
      # ASRock DeskMini 310
      # Intel Core i3-8100
      ansible_host: 192.168.1.131
    valkyrie:
      # Intel NUC D54250WYK
      # Intel Core i5-4250U
      ansible_host: 192.168.1.132
    pegasus:
      # HP EliteDesk 800 G1 DM
      # Intel Core i5-4590T
      ansible_host: 192.168.1.133
    ixion:
      # Dell Optiplex 7040M
      # Intel Core i7-6700T
      ansible_host: 192.168.1.134
    atlantia:
      # Lenovo Thinkcentre M700 Tiny
      # Intel Core i5-6400T
      ansible_host: 192.168.1.135

  children:
    rpi:
      children:
        blocky:
    blocky:
      hosts:
        osiris:
        solaria:
    debian:
      children:
        blocky:
        k8s_cluster:
    longhorn:
      hosts:
        pacifica:
        valkyrie:
        pegasus:
        ixion:
        atlantia:
    k8s_control_plane:
      hosts:
        pacifica:
        valkyrie:
        pegasus:
    k8s_workers:
      hosts:
        ixion:
        atlantia:
    k8s_cluster:
      children:
        k8s_control_plane:
        k8s_workers:
