all:
  hosts:
    galactica:
      # Silverstone CS380 (TrueNAS SCALE)
      # Ryzen 5600G
      ansible_host: 192.168.1.121

    pacifica:
      # Lenovo Thinkcentre M920q Tiny
      # Intel Core i7-8700T
      ansible_host: 192.168.1.131
    valkyrie:
      # HP ProDesk 600 G4 DM
      # Intel Core i5-8500T
      ansible_host: 192.168.1.132
    pegasus:
      #  HP EliteDesk 800 G4 DM
      # Intel Core i5-8600
      ansible_host: 192.168.1.133
    ixion:
      # Dell Optiplex 7040M
      # Intel Core i7-6700T
      ansible_host: 192.168.1.134
    atlantia:
      # Lenovo Thinkcentre M700 Tiny
      # Intel Core i7-6700T
      ansible_host: 192.168.1.135
    athena:
      # Lenovo Thinkcentre M700 Tiny
      # Intel Core i5-6400T
      ansible_host: 192.168.1.136


  children:
    debian:
      hosts:
        athena:
      children:
        k8s_cluster:
    longhorn:
      hosts:
        pacifica:
        valkyrie:
        pegasus:
        ixion:
        atlantia:
    k8s_control_plane:
      hosts:
        pacifica:
        valkyrie:
        pegasus:
    k8s_workers:
      hosts:
        ixion:
        atlantia:
        athena:
    k8s_cluster:
      children:
        k8s_control_plane:
        k8s_workers:
