all:
  hosts:
    raptor:
      ansible_host: 192.168.1.101
    osiris:
      ansible_host: 192.168.1.102
    solaria:
      ansible_host: 192.168.1.103

    galactica:
      # NAS
      ansible_host: 192.168.1.121
    pacifica:
      # DeskMini
      ansible_host: 192.168.1.122
    archeron:
      # acerslab
      ansible_host: 192.168.1.123

    valkyrie:
      ansible_host: 192.168.1.131
    pegasus:
      ansible_host: 192.168.1.132
    ixion:
      ansible_host: 192.168.1.133
    atlantia:
      ansible_host: 192.168.1.134
    rycon:
      ansible_host: 192.168.1.135

  children:
    rpi:
      hosts:
        raptor:
        osiris:
        solaria:
    blocky:
      hosts:
        osiris:
        solaria:
    ubuntu_servers:
      hosts:
        raptor:
        galactica:
        pacifica:
        archeron:
        valkyrie:
        pegasus:
        ixion:
        atlantia:
        rycon:
    longhorn_storage_nodes:
      hosts:
        valkyrie:
        pegasus:
        ixion:
        atlantia:
        rycon:
    k8s_control_plane:
      hosts:
        pacifica:
        archeron:
        raptor:
    k8s_workers:
      hosts:
        valkyrie:
        pegasus:
        ixion:
        atlantia:
        rycon:
    k8s_cluster:
      children:
        k8s_control_plane:
        k8s_workers:
