all:
  hosts:
    osiris:
      # Raspberry Pi 3 B+
      ansible_host: 192.168.1.101
      ansible_user: root
    solaria:
      # Raspberry Pi 3 B+
      ansible_host: 192.168.1.102
      ansible_user: root
    athena:
      # Raspberry Pi 4 (apcupsd)
      ansible_host: 192.168.1.107

    galactica:
      # Silverstone CS380 (TrueNAS SCALE)
      # Ryzen 5600G
      ansible_host: 192.168.1.121

    pacifica:
      # ASRock DeskMini 310
      # Intel Core i3-8100
      ansible_host: 192.168.1.131
    valkyrie:
      # HP ProDesk 600 G4 DM
      # Intel Core i5-8500T
      ansible_host: 192.168.1.132
    pegasus:
      # HP EliteDesk 800 G1 DM
      # Intel Core i5-4590T
      ansible_host: 192.168.1.133
    ixion:
      # Dell Optiplex 7040M
      # Intel Core i7-6700T
      ansible_host: 192.168.1.134
    atlantia:
      # Lenovo Thinkcentre M700 Tiny
      # Intel Core i5-6400T
      ansible_host: 192.168.1.135

  children:
    rpi:
      children:
        dns:
      hosts:
        athena:
    dns:
      hosts:
        osiris:
        solaria:
    debian:
      children:
        dns:
        k8s_cluster:
      hosts:
        athena:
    longhorn:
      hosts:
        pacifica:
        valkyrie:
        pegasus:
        ixion:
        atlantia:
    k8s_control_plane:
      hosts:
        pacifica:
        valkyrie:
        pegasus:
    k8s_workers:
      hosts:
        ixion:
        atlantia:
    k8s_cluster:
      children:
        k8s_control_plane:
        k8s_workers:
