bootstrapDns: tcp+udp:1.1.1.1:53
blocking:
  blackLists:
    ads:
      - https://raw.githubusercontent.com/AdAway/adaway.github.io/master/hosts.txt
  blockType: nxDomain
  blockTTL: 5m
  clientGroupsBlock:
    default:
      - ads
    192.168.1.111/24: []
  refreshPeriod: 60m
certFile: /app/cert.pem
customDNS:
  # send unmapped entries (non-A records) for hubbe.club to upstream resolvers
  filterUnmappedTypes: false
  mapping:
    # prevent need for NAT Reflection in firewall
    hubbe.club: 192.168.1.3
    wireguard.hubbe.club: 192.168.1.1

    # auto-detection of controller for unifi devices relies on DNS
    unifi: 192.168.1.10
    unifi.lan: 192.168.1.10

    blocky.lan: 192.168.1.100

    osiris.lan: 192.168.1.101
    solaria.lan: 192.168.1.102
    root-switch.lan: 192.168.1.103
    wifi-switch.lan: 192.168.1.104
    k8s-switch.lan: 192.168.1.105

    ma3a.lan: 192.168.1.111
    ps4.lan: 192.168.1.112

    galactica.lan: 192.168.1.121

    apiserver.lan: 192.168.1.130

    pacifica.lan: 192.168.1.131
    valkyrie.lan: 192.168.1.132
    pegasus.lan: 192.168.1.133

    ixion.lan: 192.168.1.134
    atlantia.lan: 192.168.1.135

    durandal.lan: 192.168.1.141
    shodan.lan: 192.168.1.142
httpsPort: 443
keyFile: /app/key.pem
port: 53
prometheus:
  enable: true
  path: /metrics
redis:
  address: 192.168.1.6:6379
  database: 0
  required: false
  connectionAttempts: 3
  connectionCooldown: 2s
upstream:
  default:
    # cloudflare
    - 1.1.1.1
    - 1.0.0.1
    - "2606:4700:4700::1111"
    - "2606:4700:4700::1001"
    # opendns
    - 208.67.222.222
    - 208.67.220.220
    - "2620:119:35::35"
    - "2620:119:53::53"
    # quad9
    - 9.9.9.9
    - 149.112.112.112
    - "2620:fe::fe"
    - "2620:fe::9"
    # adguard
    - 94.140.14.14
    - 94.140.15.15
    - "2a10:50c0::ad1:ff"
    - "2a10:50c0::ad2:ff"
