- name: Set facts for kube-vip template
  set_fact:
    interface_name: "{{ ansible_default_ipv4.interface }}"
    virtual_ip: "{{ control_plane_vip }}"

- name: Ensure static pod manifest folder exists
  file:
    path: /etc/kubernetes/manifests
    state: directory
    mode: 0644

- name: Deploy kube-vip static pod manifest
  become: true
  become_user: root
  template:
    src: templates/kube-vip.j2
    dest: /etc/kubernetes/manifests/kube-vip.yaml
    mode: 0644
