- name: Install required packages for official docker repo
  become: true
  become_user: root
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
    state: present
    update_cache: true

- name: Install required kernel modules on rpi
  become: true
  become_user: root
  apt:
    name: linux-modules-extra-raspi
    state: present
    update_cache: true
  when:
    - "'rpi' in group_names"
    - "'ubuntu' in group_names"

- name: "Check if reboot is required"
  register: reboot_required_file
  stat:
    path: /var/run/reboot-required

- name: "Reboot host"
  become: true
  become_user: root
  reboot:
    msg: "Reboot initiated by Ansible for kernel update"
    connect_timeout: 5
    reboot_timeout: 600
    pre_reboot_delay: 0
    post_reboot_delay: 60
    test_command: uptime
  when:
    - reboot_required_file.stat.exists

- name: Fetch docker repo signing key
  become: true
  become_user: root
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    keyring: /usr/share/keyrings/docker-archive-keyring.gpg

- name: Add docker repo to apt sources
  become: true
  become_user: root
  template:
    src: templates/docker-sources.j2
    dest: /etc/apt/sources.list.d/docker.list
    mode: 0644

- name: Install docker engine
  become: true
  become_user: root
  apt:
    name:
      - containerd.io
      - docker-ce
      - docker-ce-cli
    update_cache: true

- name: Enable docker service
  become: true
  become_user: root
  systemd:
    name: docker
    enabled: true
    state: started
