- name: Get tag name for latest release of kube-router
  community.general.github_release:
    user: cloudnativelabs
    repo: kube-router
    action: latest_release
  register: latest_release
  when:
    - inventory_hostname == groups['k8s_control_plane'][0]

- name: Fetch release manifest for kube-router
  get_url:
    url: https://raw.githubusercontent.com/cloudnativelabs/kube-router/master/daemonset/kubeadm-kuberouter.yaml
    dest: /tmp/kube-router.yaml
    mode: 0644
  when:
    - inventory_hostname == groups['k8s_control_plane'][0]

- name: Add tag name as image tag to manifest
  replace:
    path: /tmp/kube-router.yaml
    regexp: "cloudnativelabs\/kube-router"
    replace: "cloudnativelabs/kube-router:{{ latest_release.tag }}"

- name: Apply kube-router manifest
  become: true
  become_user: root
  command: "kubectl apply -f /tmp/kube-router.yaml"
  when:
    - inventory_hostname == groups['k8s_control_plane'][0]
