- name: Generate certificate key
  become: true
  become_user: root
  command: kubeadm certs certificate-key
  register: kubeadm_certs_cmd
  run_once: true
  when: "'k8s_control_plane' in group_names"

- name: Upload certificates to cluster using key
  become: true
  become_user: root
  command: "kubeadm init phase upload-certs --upload-certs --certificate-key {{ kubeadm_certs_cmd.stdout }}"
  run_once: true
  when: "'k8s_control_plane' in group_names"

- name: Generate join token
  become: true
  become_user: root
  command: kubeadm token create --print-join-command
  register: kubeadm_token_cmd
  run_once: true
  when: "'k8s_control_plane' in group_names"

- name: Join node to cluster as control-plane node
  become: true
  become_user: root
  command: "{{ kubeadm_token_cmd.stdout }} --control-plane --certificate-key {{ kubeadm_certs_cmd.stdout }}"
  when: "'k8s_control_plane' in group_names"

- name: Wait for node to be ready
  delegate_to: 127.0.0.1
  command: kubectl wait --for=condition=Ready --timeout=300s node {{ inventory_hostname }}
  when: "'k8s_control_plane' in group_names"
