- name: Generate join token
  become: true
  become_user: root
  command: kubeadm token create --print-join-command
  register: kubeadm_token_cmd
  run_once: true
  when: "'k8s_worker' in group_names"

- name: Join cluster as worker
  become: true
  become_user: root
  command: "{{ kubeadm_token_cmd.stdout }}"
  when: "'k8s_worker' in group_names"

- name: Wait for node readiness
  delegate_to: 127.0.0.1
  command: kubectl wait --for=condition=Ready --timeout=300s node {{ inventory_hostname }}
  when: "'k8s_worker' in group_names"

- name: Label node as worker
  delegate_to: 127.0.0.1
  command: kubectl label node {{ inventory_hostname }} kubernetes.io/role=worker
  when: "'k8s_worker' in group_names"
