- name: "Ensure node is reporting 'Ready' status"
  shell: "kubectl get node {{ host }} -o json|jq .status.conditions| jq -c '.[] | select(.type | contains(\"Ready\"))'|jq .status"
  register: node_status
  delegate_to: 127.0.0.1
  until: node_status.stdout.find("True") != -1
  retries: 30
  delay: 10

- name: "Uncordon node"
  command: kubectl uncordon {{ host }}
  delegate_to: 127.0.0.1

- name: "Wait for longhorn to report 'Ready' status"
  shell: "kubectl -n longhorn-system get nodes.longhorn.io {{ host }} -o json|jq .status.conditions.Ready.status"
  register: longhorn_status
  delegate_to: 127.0.0.1
  until: longhorn_status.stdout.find("True") != -1
  retries: 30
  delay: 10
  when:
    - "'k8s_worker' in group_names"

- name: "Re-enable longhorn replica scheduling"
  command: "kubectl -n longhorn-system patch nodes.longhorn.io {{ host }} --patch '{\"spec\": {\"allowScheduling\": true, \"evictionRequested\": false}}' --type=merge"
  delegate_to: 127.0.0.1
  when:
    - "'k8s_worker' in group_names"
