- name: "Check if longhorn is deployed"
  command: kubectl get ns longhorn-system
  register: longhorn_deployed_cmd
  delegate_to: 127.0.0.1
  failed_when: "longhorn_deployed_cmd.rc not in [ 0, 1 ]"
  when:
    - "'k8s_cluster' in group_names"

- name: "Wait for node to be ready"
  command: "kubectl wait --for=condition=Ready --timeout=300s node {{ host }}"
  delegate_to: 127.0.0.1
  when:
    - longhorn_deployed_cmd.rc != 1
    - "'k8s_cluster' in group_names"

- name: "Uncordon node"
  command: kubectl uncordon {{ host }}
  delegate_to: 127.0.0.1
  when:
    - "'k8s_cluster' in group_names"

- name: "Wait for longhorn to report 'Ready' status"
  shell: |
    set -o pipefail && \
    kubectl -n longhorn-system get nodes.longhorn.io {{ host }} -o json|jq .status.conditions.Ready.status
  register: longhorn_status
  delegate_to: 127.0.0.1
  until: longhorn_status.stdout.find("True") != -1
  retries: 30
  delay: 10
  when:
    - longhorn_deployed_cmd.rc != 1
    - "'longhorn' in group_names"
