- hosts: blocky
  serial: 1
  become: true
  become_user: root
  tasks:
    - name: Install podman
      apt:
        name: podman
        state: present
    # deploy blocky config
    - name: Ensure blocky dir exists
      file:
        path: /etc/blocky
        state: directory
        mode: 0755
    - name: Deploy blocky config
      copy:
        src: files/blocky/config.yml
        dest: /etc/blocky/config.yml
        mode: 0644
      register: config
    - name: Deploy blocky SSL cert
      copy:
        src: files/blocky/cert.pem
        dest: /etc/blocky/cert.pem
        mode: 0644
      register: cert
    - name: Deploy blocky SSL key
      copy:
        src: files/blocky/key.pem
        dest: /etc/blocky/key.pem
        mode: 0644
      register: key

    - name: Deploy blocky container
      containers.podman.podman_container:
        name: blocky
        image: ghcr.io/0xerr0r/blocky:v0.19
        generate_systemd:
          path: /etc/systemd/system/
          restart_policy: always
        network: host
        restart_policy: always
        state: started
        volume:
          - /etc/blocky/config.yml:/app/config.yml
          - /etc/blocky/cert.pem:/app/cert.pem
          - /etc/blocky/key.pem:/app/key.pem

    - name: Set up blocky service
      systemd:
        daemon_reload: true
        name: container-blocky
        enabled: true
        state: started

    - name: Restart blocky to pick up config changes
      systemd:
        name: container-blocky
        state: restarted
      when: config.changed or cert.changed or key.changed

    # deploy keepalived config
    - name: Ensure keepalived dir exists
      file:
        path: /etc/keepalived
        state: directory
        mode: 0755
    - name: Deploy keepalived.conf if primary DNS
      copy:
        src: files/blocky/keepalived_primary.conf
        dest: /etc/keepalived/keepalived.conf
        mode: 0644
      when: inventory_hostname == groups['blocky'][0]
      register: primary_config
    - name: Deploy keepalived.conf if secondary DNS
      copy:
        src: files/blocky/keepalived_secondary.conf
        dest: /etc/keepalived/keepalived.conf
        mode: 0644
      when: inventory_hostname != groups['blocky'][0]
      register: secondary_config
    - name: Create keepalived_script user
      user:
        name: keepalived_script
        create_home: false
        system: true
    - name: Ensure keepalive script folder exists
      file:
        path: /etc/keepalived_scripts
        state: directory
        mode: 0755
        owner: keepalived_script
        group: keepalived_script
    - name: Deploy DNS check script
      copy:
        src: files/blocky/check_dns.sh
        dest: /etc/keepalived_scripts/check_dns.sh
        mode: 0700
        owner: keepalived_script
        group: keepalived_script
      register: check_script

    # ensure keepalived is installed
    - name: Install keepalived
      apt:
        name: keepalived
        state: present

    # ensure 'dig' command is available
    - name: Install dnsutils
      apt:
        name: bind9-dnsutils
        state: present

    # ensure it's running
    - name: Set up keepalived service
      systemd:
        name: keepalived
        enabled: true
        state: started

    - name: Restart keepalived to pick up config changes
      systemd:
        name: keepalived
        state: restarted
      when: (inventory_hostname == groups['blocky'][0] and primary_config.changed) or (inventory_hostname != groups['blocky'][0] and secondary_config.changed) or check_script.changed

    - name: Wait before updating next host to ensure DNS availability
      pause:
        seconds: 15
