- hosts: "{{ inventory_hosts }}"
  # limit to handle only one host at a time
  serial: 1
  vars_prompt:
    - name: "inventory_hosts"
      prompt: "Deploy kube-vip static pod to which host(s)?"
      private: false
  vars_files:
    - vars/install_settings.yaml
  tasks:
    - name: Deploy pod manifest
      import_tasks: tasks/deploy-kube-vip.yaml
