- hosts: "{{ inventory_hosts }}"
  # limit to handle only one host at a time
  serial: 1
  vars_prompt:
    - name: "inventory_hosts"
      prompt: "Deploy kube-vip static pod to which host(s)?"
      private: false
  vars_files:
    - vars/install_settings.yaml
  tasks:
    - name: Set facts for kube-vip template
      set_fact:
        interface_name: "{{ ansible_default_ipv4.interface }}"
        virtual_ip: "{{ control_plane_vip }}"

    - name: Deploy kube-vip static pod manifest
      become: true
      become_user: root
      template:
        src: templates/kube-vip.j2
        dest: /etc/kubernetes/manifests/kube-vip.yaml
        mode: 0644
