- hosts: "{{ inventory_hosts }}"
  ignore_unreachable: true
  serial: 1
  vars_prompt:
    - name: "inventory_hosts"
      prompt: "Deploy resolv.conf and .ssh/authorized keys to which host or group in inventory?"
  tasks:
    - name: Disable and stop systemd-resolved
      become: true
      become_user: root
      systemd:
        name: systemd-resolved
        enabled: false
        state: stopped
    - name: Check if /etc/resolv.conf is a symlink
      become: true
      become_user: root
      stat:
        path: /etc/resolv.conf
      register: resolvconf
    - name: Remove /etc/resolv.conf symlink
      become: true
      become_user: root
      file:
        follow: false
        path: /etc/resolv.conf
        state: absent
      when: resolvconf.stat.islnk is defined and resolvconf.stat.islnk
    - name: Deploy /etc/resolv.conf
      become: true
      become_user: root
      copy:
        content: |
          nameserver 192.168.1.100
          search lan
        dest: /etc/resolv.conf
        mode: 0644

    - name: Ensure .ssh dir exists
      file:
        path: ~/.ssh
        state: directory
        mode: 0755
    - name: Deploy authorized_keys
      copy:
        content: |
          ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGCOz0rEqX5SdB6fE7CV73m15e1MFKcdM1YXsmhwqlbW hubbe@desktop
          ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFJ1zIkbSsy/2Tjb3HKn1qW9hPGYpVgbXvM1LXTsu3cz hubbe@laptop
          ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEx5g6m5V+1zW6wIyx3CTEovDT09hXxR+WfM4Ti0lHGQ hubbe@phone
          ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICzhOBSge/z/Gkz/OkTOubX3iO2QV4zUTtiuUKBgv4xs hubbe@pacifica
          ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMk8XNvVsGyYZrwgRVuZZ2ecINm7UZZhtpMOQ+uuyp6z hubbe@archeron
          ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGbmKD3NCDNGwzMQnZP8x8oOYG0QmC0YrexRBrBbVAMR hubbe@raptor
        dest: ~/.ssh/authorized_keys
        mode: 0600
