- hosts: "{{ inventory_hosts }}"
  serial: 1
  vars_prompt:
    - name: "inventory_hosts"
      prompt: "Run do-release-upgrade on which host or group in inventory?"
      private: false
  tasks:

    - name: Ensure update-manager is up to date
      become: true
      become_user: root
      apt:
        name: update-manager-core
        upgrade: full
        update_cache: true
      when:
        - "'ubuntu_servers' in group_names"

    - name: "Check if there is a new release"
      become: true
      become_user: root
      command: do-release-upgrade -c
      register: upgrade_check_cmd
      when:
        - "'ubuntu_servers' in group_names"

    - name: "Run release upgrade"
      become: true
      become_user: root
      command: do-release-upgrade -f DistUpgradeViewNonInteractive
      when:
        - "'ubuntu_servers' in group_names"
        - upgrade_check_cmd.rc == 1

    - name: "Check if reboot is required"
      register: reboot_required_file
      stat:
        path: /var/run/reboot-required

      # drain node
    - import_tasks: tasks/drain-node.yaml
      vars:
        host: "{{ inventory_hostname }}"
      when:
        - reboot_required_file.stat.exists
        - "'k8s_cluster' in group_names"

    - name: "Reboot host"
      become: true
      become_user: root
      reboot:
        msg: "Reboot initiated by Ansible for release upgrade"
        connect_timeout: 5
        reboot_timeout: 600
        pre_reboot_delay: 0
        post_reboot_delay: 60
        test_command: uptime
      when:
        - reboot_required_file.stat.exists

    # uncordon node
    - import_tasks: tasks/uncordon-node.yaml
      vars:
        host: "{{ inventory_hostname }}"
      when: "'k8s_cluster' in group_names"
