- hosts: "{{ inventory_hosts }}"
  serial: 1
  vars_prompt:
    - name: "inventory_hosts"
      prompt: "Upgrade packages on which host or group in inventory?"
      private: no
  tasks:
    - name: "Run full upgrade"
      become: true
      become_user: root
      apt:
        upgrade: full
        update_cache: "yes"

    - name: "Check if reboot is required"
      become: true
      become_user: root
      register: reboot_required_file
      stat: path=/var/run/reboot-required get_md5=no

    # drain node if reboot is required
    - import_tasks: tasks/drain_node.yaml
      vars:
        host: "{{ inventory_hostname }}"
      when:
        - "'k8s_cluster' in group_names"
        - reboot_required_file.stat.exists

    - name: "Reboot host"
      become: true
      become_user: root
      reboot:
        msg: "Reboot initiated by Ansible for kernel update"
        connect_timeout: 5
        reboot_timeout: 600
        pre_reboot_delay: 0
        post_reboot_delay: 60
        test_command: uptime
      when: reboot_required_file.stat.exists

    # uncordon node
    - import_tasks: tasks/uncordon_node.yaml
      vars:
        host: "{{ inventory_hostname }}"
      when: "'k8s_cluster' in group_names"
