- hosts: "{{ inventory_hosts }}"
  name: Upgrade packages on host(s)
  serial: 1
  vars_prompt:
    - name: "inventory_hosts"
      prompt: "Upgrade packages on which host or group in inventory?"
      private: false
    - name: "containerd_upgrade"
      prompt: "Upgrade containerd as well during upgrade? (y/N)"
      default: "N"
      private: false
  tasks:
    - name: "Run full upgrade"
      become: true
      become_user: root
      ansible.builtin.apt:
        upgrade: full
        update_cache: true
    # upgrade containerd.io
    - name: "Upgrade containerd.io"
      become: true
      become_user: root
      ansible.builtin.apt:
        name: containerd.io
        state: latest
        update_cache: true
        allow_change_held_packages: true
      when: containerd_upgrade | bool

    - name: "Hold containerd package"
      become: true
      become_user: root
      ansible.builtin.dpkg_selections:
        name: containerd.io
        selection: hold

    - name: "Check if reboot is required"
      register: reboot_required_file
      ansible.builtin.stat:
        path: /var/run/reboot-required

    # drain node
    - name: Drain node of workloads
      ansible.builtin.import_tasks: tasks/drain-node.yaml
      vars:
        host: "{{ inventory_hostname }}"
      when:
        - "'k8s_cluster' in group_names"
        - reboot_required_file.stat.exists

    - name: "Reboot host"
      become: true
      become_user: root
      ansible.builtin.reboot:
        msg: "Reboot initiated by Ansible for kernel update"
        connect_timeout: 5
        reboot_timeout: 600
        pre_reboot_delay: 0
        post_reboot_delay: 60
        test_command: uptime
      when:
        - reboot_required_file.stat.exists

    # uncordon node
    - name: Ready node for workloads
      ansible.builtin.import_tasks: tasks/uncordon-node.yaml
      vars:
        host: "{{ inventory_hostname }}"
      when:
        - "'k8s_cluster' in group_names"
        - reboot_required_file.stat.exists
