- hosts: "{{ inventory_hosts }}"
  serial: 1
  vars_prompt:
    - name: "inventory_hosts"
      prompt: "Upgrade packages on which host or group in inventory?"
      private: false
  tasks:
    - name: "Run full upgrade"
      become: true
      become_user: root
      apt:
        upgrade: full
        update_cache: true

    - name: "Check if reboot is required"
      register: reboot_required_file
      stat:
        path: /var/run/reboot-required

    # drain node
    - import_tasks: tasks/drain-node.yaml
      vars:
        host: "{{ inventory_hostname }}"
      when:
        - "'k8s_cluster' in group_names"
        - reboot_required_file.stat.exists

    - name: "Reboot host"
      become: true
      become_user: root
      reboot:
        msg: "Reboot initiated by Ansible for kernel update"
        connect_timeout: 5
        reboot_timeout: 600
        pre_reboot_delay: 0
        post_reboot_delay: 60
        test_command: uptime
      when:
        - reboot_required_file.stat.exists

    # uncordon node
    - import_tasks: tasks/uncordon-node.yaml
      vars:
        host: "{{ inventory_hostname }}"
      when:
        - "'k8s_cluster' in group_names"
        - reboot_required_file.stat.exists
