- hosts: ceph
  tasks:
    - name: "Run full upgrade"
      become: true
      become_user: root
      apt:
        upgrade: full
        update_cache: true
    - name: "Check if reboot is required"
      register: reboot_required_file
      stat:
        path: /var/run/reboot-required
    - name: "Reboot host"
      become: true
      become_user: root
      reboot:
        msg: "Reboot initiated by Ansible for kernel update"
        connect_timeout: 5
        reboot_timeout: 600
        pre_reboot_delay: 0
        post_reboot_delay: 60
        test_command: uptime
      when:
        - reboot_required_file.stat.exists
    - name: Install ceph packages
      become: true
      become_user: root
      with_items:
        - cephadm
        - ceph-common
        - podman
      apt:
        name: "{{ item }}"
        state: present
        autoremove: true
        purge: true
        update_cache: true
