- hosts: ceph
  tasks:
    - name: "Run full upgrade"
      become: true
      become_user: root
      apt:
        upgrade: full
        update_cache: true
    # https://forums.raspberrypi.com/viewtopic.php?t=245931
    - name: "Blacklist UAS for flaky SABRENT devices"
      become: true
      become_user: root
      replace:
        backup: true
        dest: /boot/cmdline.txt
        mode: 0644
        regexp: "^console=serial0,115200.*"
        replace: "usb-storage.quirks=152d:1561:u console=serial0,115200"
      register: cmdline

    - name: "Check if reboot is required"
      register: reboot_required_file
      stat:
        path: /var/run/reboot-required
    - name: "Reboot host"
      become: true
      become_user: root
      reboot:
        msg: "Reboot initiated by Ansible for kernel update"
        connect_timeout: 5
        reboot_timeout: 600
        pre_reboot_delay: 0
        post_reboot_delay: 60
        test_command: uptime
      when: reboot_required_file.stat.exists or cmdline.changed

    - name: Deploy SSD udev rule
      become: true
      become_user: root
      copy:
        src: files/60-ssd-scheduler.rules
        dest: /etc/udev/rules.d/60-ssd-scheduler.rules
        mode: 0644
      notify:
        - Reload udev rules
    - name: Install glusterfs
      become: true
      become_user: root
      with_items:
        - glusterfs-server
      apt:
        name: "{{ item }}"
        state: present
        update_cache: true
    - name: Create LVM volume groups
      become: true
      become_user: root
      with_items:
        - /dev/sda
        - /dev/sdb
      community.general.lvg:
        pvs: "{{ item }}"
        vg: "data.{{ item | basename }}"
    - name: Create LVM thinpools
      become: true
      become_user: root
      with_items:
        - data.sda
        - data.sdb
      community.general.lvol:
        thinpool: "{{ item }}-pool"
        vg: "{{ item }}"
    - name: Create LVM bricks
      become: true
      become_user: root
      with_items:
        - data.sda
        - data.sdb
      community.general.lvol:
        lv: brick
        size: 450G
        thinpool: "{{ item }}-pool"
        vg: "{{ item }}"
    - name: Set up XFS on LVM bricks
      become: true
      become_user: root
      with_items:
        - /dev/data.sda/brick
        - /dev/data.sdb/brick
      community.general.filesystem:
        dev: "{{ item }}"
        fstype: xfs
    - name: Create mount points for LVM bricks
      become: true
      become_user: root
      with_items:
        - /data/sda/brick
        - /data/sdb/brick
      file:
        path: "{{ item }}"
        mode: 0755
        state: directory
    - name: Set up fstab rules for LVM bricks
      become: true
      become_user: root
      with_items:
        - sda
        - sdb
      lineinfile:
        path: /etc/fstab
        line: "/dev/data.{{ item }}/brick /data/{{ item }}/brick xfs defaults 0 0"
    - name: Mount LVM bricks
      become: true
      become_user: root
      command:
        cmd: mount -a
    - name: Enable & Start GlusterFS server
      become: true
      become_user: root
      systemd:
        name: glusterd
        enabled: true
        state: started

  handlers:
    - name: Reload udev rules
      become: true
      become_user: root
      command:
        cmd: udevadm control --reload-rules
