- hosts: rpi
  name: Prepare Debian RPi nodes for k3s/k0s cluster-up
  tasks:
    - name: Run full upgrade
      ansible.builtin.apt:
        upgrade: full
        update_cache: true
    - name: Install htop, iptables, and kitty-terminfo
      ansible.builtin.apt:
        name:
          - htop
          - iptables
          - kitty-terminfo
        state: present
    - name: Set hostname
      ansible.builtin.copy:
        content: "{{ inventory_hostname }}"
        dest: /etc/hostname
        mode: 0644
      notify:
        - Reboot host
    - name: Set hosts
      ansible.builtin.lineinfile:
        line: "127.0.1.1 {{ inventory_hostname }}"
        mode: 0644
        path: /etc/hosts
    - name: Deploy sshd config
      ansible.builtin.copy:
        src: files/sshd_config
        dest: /etc/ssh/sshd_config
        mode: 0644
      notify:
        - Restart sshd
    - name: Ensure .ssh dir exists
      ansible.builtin.file:
        path: ~/.ssh
        state: directory
        mode: 0755
    - name: Deploy authorized_keys
      ansible.builtin.copy:
        src: files/authorized_keys
        dest: ~/.ssh/authorized_keys
        mode: 0600
    - name: Deploy SSD udev rule
      ansible.builtin.copy:
        src: files/60-ssd-scheduler.rules
        dest: /etc/udev/rules.d/60-ssd-scheduler.rules
        mode: 0644
      notify:
        - Reload udev rules
    - name: Check which iptables is in use
      ansible.builtin.command:
        cmd: which iptables
      register: which_iptables
      when: true
    # https://docs.k3s.io/advanced#additional-preparation-for-debian-buster-based-distributions
    - name: Switch to legacy iptables
      with_items:
        - iptables -F
        - update-alternatives --set iptables /usr/sbin/iptables-legacy
        - update-alternatives --set ip6tables /usr/sbin/ip6tables-legacy
      ansible.builtin.command:
        cmd: "{{ item }}"
      when:
        - which_iptables.stdout.find("/usr/sbin/iptables-legacy") == -1
      notify:
        - Reboot node
    - name: Check if reboot is required for package upgrade
      register: reboot_required_file
      ansible.builtin.stat:
        path: /var/run/reboot-required
      notify:
        - Reboot host
  handlers:
    - name: Reload udev rules
      ansible.builtin.command:
        cmd: udevadm control --reload-rules
    - name: Restart sshd
      ansible.builtin.systemd:
        name: sshd.service
        enabled: true
        state: restarted
    - name: Reboot host
      ansible.builtin.reboot:
        msg: Reboot initiated by Ansible
        connect_timeout: 5
        reboot_timeout: 600
        pre_reboot_delay: 0
        post_reboot_delay: 60
        test_command: uptime
