- hosts: storage
  tasks:
    - name: Run full upgrade
      apt:
        upgrade: full
        update_cache: true
    - name: Install htop and kitty-terminfo
      apt:
        name: 
          - htop
          - kitty-terminfo
        state: present
    # https://forums.raspberrypi.com/viewtopic.php?t=245931
    - name: Blacklist UAS for flaky SABRENT devices
      copy:
        content: |
          usb-storage.quirks=152d:1561:u console=tty0 console=ttyS1,115200 root=LABEL=RASPIROOT rw fsck.repair=yes net.ifnames=0 rootwait
        dest: /boot/firmware/cmdline.txt
        mode: 0644
      register: cmdline
    - name: Set hostname
      copy:
        content: "{{ inventory_hostname }}"
        dest: /etc/hostname
      register: hostname
    - name: Set hosts
      lineinfile:
        line: "127.0.1.1 {{ inventory_hostname }}"
        mode: 0644
        path: /etc/hosts
    - name: Deploy sshd config
      copy:
        src: files/sshd_config
        dest: /etc/ssh/sshd_config
        mode: 0644
      notify:
        - Restart sshd
    - name: Check if reboot is required for package upgrade
      register: reboot_required_file
      stat:
        path: /var/run/reboot-required
    - name: Reboot host
      reboot:
        msg: Reboot initiated by Ansible for kernel update
        connect_timeout: 5
        reboot_timeout: 600
        pre_reboot_delay: 0
        post_reboot_delay: 60
        test_command: uptime
      when: reboot_required_file.stat.exists or cmdline.changed or hostname.changed
    - name: Deploy SSD udev rule
      copy:
        src: files/60-ssd-scheduler.rules
        dest: /etc/udev/rules.d/60-ssd-scheduler.rules
        mode: 0644
      notify:
        - Reload udev rules
    - name: Install ceph packages
      apt:
        name:
        - ceph-common
        - cephadm
        - podman
        update_cache: true
  handlers:
    - name: Reload udev rules
      become: true
      become_user: root
      command:
        cmd: udevadm control --reload-rules
    - name: Restart sshd
      systemd:
        name: sshd.service
        enabled: true
        state: restarted
