- hosts: "{{ inventory_hosts }}"
  serial: 1
  gather_facts: false
  vars_prompt:
    - name: "inventory_hosts"
      prompt: "Ready which host or group in inventory?"
  tasks:
    - name: "Wait for host to become reachable"
      wait_for_connection:
        timeout: 600  # 10 minutes

    - name: "Gather facts"
      setup:

    - import_tasks: tasks/uncordon_node.yaml
      vars:
        host: "{{ inventory_hostname }}"
      when: "'k8s_cluster' in group_names"
