- hosts: "{{ inventory_hosts }}"
  serial: 1
  vars_prompt:
    - name: "inventory_hosts"
      prompt: "Reboot which host or group in inventory?"
  tasks:
    - import_tasks: tasks/drain_node.yaml
      vars:
        host: "{{ inventory_hostname }}"
      when: "'k8s_cluster' in group_names"

    - name: "Reboot host"
      become: true
      become_user: root
      reboot:
        msg: "Reboot initiated by Ansible"
        connect_timeout: 5
        reboot_timeout: 600
        pre_reboot_delay: 0
        post_reboot_delay: 60
        test_command: uptime

    - import_tasks: tasks/uncordon_node.yaml
      vars:
        host: "{{ inventory_hostname }}"
      when: "'k8s_cluster' in group_names"
