- hosts: storage
  tasks:
    - name: "Run full upgrade"
      become: true
      become_user: root
      apt:
        upgrade: full
        update_cache: true
    # https://forums.raspberrypi.com/viewtopic.php?t=245931
    - name: "Blacklist UAS for flaky SABRENT devices"
      become: true
      become_user: root
      replace:
        backup: true
        dest: /boot/cmdline.txt
        mode: 0644
        regexp: "^console=serial0,115200.*"
        replace: "usb-storage.quirks=152d:1561:u console=serial0,115200"
      register: cmdline
    - name: "Check if reboot is required"
      register: reboot_required_file
      stat:
        path: /var/run/reboot-required
    - name: "Reboot host"
      become: true
      become_user: root
      reboot:
        msg: "Reboot initiated by Ansible for kernel update"
        connect_timeout: 5
        reboot_timeout: 600
        pre_reboot_delay: 0
        post_reboot_delay: 60
        test_command: uptime
      when: reboot_required_file.stat.exists or cmdline.changed
    - name: Deploy SSD udev rule
      become: true
      become_user: root
      copy:
        src: files/60-ssd-scheduler.rules
        dest: /etc/udev/rules.d/60-ssd-scheduler.rules
        mode: 0644
      notify:
        - Reload udev rules
    - name: Disable & Stop GlusterFS server
      become: true
      become_user: root
      systemd:
        name: glusterd
        enabled: false
        state: stopped
    - name: Unmount LVM bricks
      become: true
      become_user: root
      with_items:
        - /data/sda/brick
        - /data/sdb/brick
      ansible.posix.mount:
        path: "{{ item }}"
        state: absent
    - name: Delete LVM bricks
      become: true
      become_user: root
      with_items:
        - data.sda
        - data.sdb
      community.general.lvol:
        force: true
        lv: brick
        state: absent
        thinpool: "{{ item }}-pool"
        vg: "{{ item }}"
    - name: Delete LVM thinpools
      become: true
      become_user: root
      with_items:
        - data.sda
        - data.sdb
      community.general.lvol:
        force: true
        state: absent
        thinpool: "{{ item }}-pool"
        vg: "{{ item }}"
    - name: Delete LVM volume groups
      become: true
      become_user: root
      with_items:
        - /dev/sda
        - /dev/sdb
      community.general.lvg:
        force: true
        state: absent
        pvs: "{{ item }}"
        vg: "data.{{ item | basename }}"
    - name: Wipe drives
      become: true
      become_user: root
      with_items:
        - /dev/sda
        - /dev/sdb
      command:
        cmd: "wipefs --all {{ item }}"
    - name: Uninstall glusterfs
      become: true
      become_user: root
      apt:
        name: glusterfs-server
        purge: true
        state: absent
  handlers:
    - name: Reload udev rules
      become: true
      become_user: root
      command:
        cmd: udevadm control --reload-rules
