- hosts: storage
  tasks:
    - name: Disable & Stop GlusterFS server
      systemd:
        name: glusterd
        enabled: false
        state: stopped
    - name: Unmount LVM bricks
      with_items:
        - /data/sda/brick
        - /data/sdb/brick
      ansible.posix.mount:
        path: "{{ item }}"
        state: absent
    - name: Delete LVM bricks
      with_items:
        - data.sda
        - data.sdb
      community.general.lvol:
        force: true
        lv: brick
        state: absent
        thinpool: "{{ item }}-pool"
        vg: "{{ item }}"
    - name: Delete LVM thinpools
      with_items:
        - data.sda
        - data.sdb
      community.general.lvol:
        force: true
        state: absent
        thinpool: "{{ item }}-pool"
        vg: "{{ item }}"
    - name: Delete LVM volume groups
      with_items:
        - /dev/sda
        - /dev/sdb
      community.general.lvg:
        force: true
        state: absent
        pvs: "{{ item }}"
        vg: "data.{{ item | basename }}"
    - name: Wipe drives
      with_items:
        - /dev/sda
        - /dev/sdb
      command:
        cmd: "wipefs --all {{ item }}"
    - name: Uninstall glusterfs
      apt:
        name: glusterfs-server
        purge: true
        state: absent
  handlers:
    - name: Reload udev rules
      command:
        cmd: udevadm control --reload-rules
