- hosts: "{{ inventory_hosts }}"
  name: Update kubelet config file on node(s)
  serial: 1
  vars_prompt:
    - name: "inventory_hosts"
      prompt: "Which hosts?"
      private: false
  tasks:
    - name: Deploy kubelet config
      become: true
      become_user: root
      ansible.builtin.copy:
        src: files/kubelet.yaml
        dest: /var/lib/kubelet/config.yaml
        mode: 0644
      notify:
        - Drain node of workloads
        - Restart kubelet
        - Ready node for workloads
  handlers:
    - name: Drain node of workloads
      ansible.builtin.import_tasks: tasks/drain-node.yaml
      vars:
        host: "{{ inventory_hostname }}"
    - name: Restart kubelet
      become: true
      become_user: root
      ansible.builtin.systemd:
        daemon_reload: true
        enabled: true
        name: kubelet
        state: restarted
    - name: Ready node for workloads
      ansible.builtin.import_tasks: tasks/uncordon-node.yaml
      vars:
        host: "{{ inventory_hostname }}"
