- hosts: "{{ inventory_hosts }}"
  name: Update kubelet config file on node(s)
  serial: 1
  vars_prompt:
    - name: "inventory_hosts"
      prompt: "Which hosts?"
      private: false
  tasks:
    - name: Deploy kubelet config
      become: true
      become_user: root
      ansible.builtin.copy:
        src: files/kubelet.yaml
        dest: /var/lib/kubelet/config.yaml
        mode: 0644
      register: config
    - name: Drain node
      import_tasks: tasks/drain-node.yaml
      vars:
        host: "{{ inventory_hostname }}"
      when: config.changed
    - name: Restart kubelet
      become: true
      become_user: root
      ansible.builtin.systemd:
        daemon_reload: true
        enabled: true
        name: kubelet
        state: restarted
      when: config.changed
    - name: Uncordon node
      import_tasks: tasks/uncordon-node.yaml
      vars:
        host: "{{ inventory_hostname }}"
      when: config.changed
