- hosts: "{{ inventory_hosts }}"
  name: Run package upgrade and shut down host
  serial: 1
  vars_prompt:
    - name: "inventory_hosts"
      prompt: "Upgrade packages on which host or group in inventory?"
      private: false
    - name: "crio_upgrade"
      prompt: "Upgrade CRI-O as well during upgrade? (y/N)"
      default: "N"
      private: false
  tasks:
    - name: "Run full upgrade"
      become: true
      become_user: root
      ansible.builtin.apt:
        upgrade: full
        update_cache: true

    # upgrade CRI-O
    - name: "Upgrade cri-o"
      become: true
      become_user: root
      ansible.builtin.apt:
        name: cri-o
        state: latest
        update_cache: true
        allow_change_held_packages: true
      when: crio_upgrade | bool

    - name: "Hold cri-o package"
      become: true
      become_user: root
      ansible.builtin.dpkg_selections:
        name: cri-o
        selection: hold

    # drain node
    - name: Drain node of workloads
      ansible.builtin.import_tasks: tasks/drain-node.yaml
      vars:
        host: "{{ inventory_hostname }}"
      when:
        - "'k8s_cluster' in group_names"

    - name: "Shut down host"
      become: true
      become_user: root
      community.general.shutdown:
